#!/bin/sh
exec 2>&1

set -e

mkdir -p /data/gpg
chmod 700 /data/gpg
chown -R www-data:www-data /data

if [ ! -e /data/firstrun ]; then
  # Initialise database
  /opt/rt4/sbin/rt-setup-database --action init --skip-create

  # Initialise database for repeatticket extension
  cd /src/rt-extension-repeatticket
  /opt/rt4/sbin/rt-setup-database \
    --action insert \
    --datadir etc \
    --datafile etc/initialdata \
    --skip-create \
    --package RT::Extension::RepeatTicket
  cd -

  # Set up full text indexing
  yes '' |
  /opt/rt4/sbin/rt-setup-fulltext-index \
    --dba rt_user \
    --dba-password "$RT_DATABASE_PW"

  touch /data/firstrun
fi

exec /usr/bin/spawn-fcgi \
  -n \
  -s /var/run/rt-server.sock \
  -u www-data \
  -U www-data \
  -G www-data \
  -M 0700 \
  -- /opt/rt4/sbin/rt-server.fcgi
