#!/bin/sh
exec 2>&1


#these are expected to be passed in via docker -e
if [ -z ${RELAY_IP} ];
then
    RELAY_IP=$(route -n | awk /UG/'{print $2}' | head -1)
fi

sed -e "s/RELAY_IP/${RELAY_IP}/g" -i /etc/postfix/main.cf
sed -e "s/WEB_DOMAIN/${WEB_DOMAIN}/g" -i /etc/postfix/main.cf
sed -e "s/WEB_DOMAIN/${WEB_DOMAIN}/g" -i /etc/postfix/procmailrc.rt

command_directory=$(postconf -h command_directory)
daemon_directory=$("$command_directory"/postconf -h daemon_directory)

# make consistency check
"$command_directory"/postfix check

# run Postfix
exec "$daemon_directory"/master
